import type { Metadata } from "next";
import { Questrial, Rubik } from "next/font/google";
import "./globals.css";
import Header from "@/app/common/Header";
import Footer from "@/app/common/Footer";

const questrial = Questrial({
  variable: "--font-questrial-sans",
    weight: "400",
  subsets: ["latin"],
});

const rubik = Rubik({
  variable: "--font-rubik-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${questrial.variable} ${rubik.variable} antialiased`}
      >
      <Header />
        {children}
      <Footer />
      </body>
    </html>
  );
}
